INSERT INTO productos (nombre  ,descripcion) values ('Panasonic','Televisores');
INSERT INTO productos (nombre  ,descripcion) values ('Sony','Gadget');
INSERT INTO productos (nombre  ,descripcion) values ('Apple','Computacion');
INSERT INTO productos (nombre  ,descripcion) values ('Sony Notebook','Electonica');
INSERT INTO productos (nombre  ,descripcion) values ('Hewlett Packard','computacion');
INSERT INTO productos (nombre  ,descripcion) values ('Bianchi','Chocolate');
INSERT INTO productos (nombre  ,descripcion) values ('Nike','Ropa y Zapatos');
INSERT INTO productos (nombre  ,descripcion) values ('Adidas','Ropa');
INSERT INTO productos (nombre  ,descripcion) values ('Reebok','deportivo');
INSERT INTO productos (nombre  ,descripcion) values ('Lenovo','Laptop');